# permissions for end users to view p2codeschedulingmanifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: p2code-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: p2codeschedulingmanifest-viewer-role
rules:
- apiGroups:
  - scheduling.p2code.eu
  resources:
  - p2codeschedulingmanifests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.p2code.eu
  resources:
  - p2codeschedulingmanifests/status
  verbs:
  - get
