//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2CodeSchedulingManifest) DeepCopyInto(out *P2CodeSchedulingManifest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2CodeSchedulingManifest.
func (in *P2CodeSchedulingManifest) DeepCopy() *P2CodeSchedulingManifest {
	if in == nil {
		return nil
	}
	out := new(P2CodeSchedulingManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *P2CodeSchedulingManifest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2CodeSchedulingManifestList) DeepCopyInto(out *P2CodeSchedulingManifestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]P2CodeSchedulingManifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2CodeSchedulingManifestList.
func (in *P2CodeSchedulingManifestList) DeepCopy() *P2CodeSchedulingManifestList {
	if in == nil {
		return nil
	}
	out := new(P2CodeSchedulingManifestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *P2CodeSchedulingManifestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2CodeSchedulingManifestSpec) DeepCopyInto(out *P2CodeSchedulingManifestSpec) {
	*out = *in
	if in.GlobalAnnotations != nil {
		in, out := &in.GlobalAnnotations, &out.GlobalAnnotations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadAnnotations != nil {
		in, out := &in.WorkloadAnnotations, &out.WorkloadAnnotations
		*out = make([]WorkloadAnnotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2CodeSchedulingManifestSpec.
func (in *P2CodeSchedulingManifestSpec) DeepCopy() *P2CodeSchedulingManifestSpec {
	if in == nil {
		return nil
	}
	out := new(P2CodeSchedulingManifestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2CodeSchedulingManifestStatus) DeepCopyInto(out *P2CodeSchedulingManifestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Decisions != nil {
		in, out := &in.Decisions, &out.Decisions
		*out = make([]SchedulingDecision, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2CodeSchedulingManifestStatus.
func (in *P2CodeSchedulingManifestStatus) DeepCopy() *P2CodeSchedulingManifestStatus {
	if in == nil {
		return nil
	}
	out := new(P2CodeSchedulingManifestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingDecision) DeepCopyInto(out *SchedulingDecision) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingDecision.
func (in *SchedulingDecision) DeepCopy() *SchedulingDecision {
	if in == nil {
		return nil
	}
	out := new(SchedulingDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAnnotation) DeepCopyInto(out *WorkloadAnnotation) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAnnotation.
func (in *WorkloadAnnotation) DeepCopy() *WorkloadAnnotation {
	if in == nil {
		return nil
	}
	out := new(WorkloadAnnotation)
	in.DeepCopyInto(out)
	return out
}
